# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  ACR: 'olgaacr.azurecr.io'
  BuildID: $(Build.BuildId)

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      deployment.yaml
    tokenPrefix: __
    tokenSuffix: __


    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: app/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        includeLatestTag: true
        tags: |
          $(tag)

    - task: CopyFiles@2
      inputs:
      #sourceFolder: # Optional
        contents: 'deployment.yaml' 
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: deploy
        publishLocation: Container
